/**
 * Re-exports the frozen, generated OpenAPI types (Phase UI-2 item 4:
 * contract/openapi.json -> contract/types.gen.ts, regenerated by
 * `npm run generate` in contract/ and checked by CI for drift). Type-only,
 * so this never triggers a real file fetch through Vite's dev server -- tsc
 * resolves and erases it entirely at compile time, unlike a runtime import
 * would.
 */
export type { components, paths } from "../../../../contract/types.gen.ts";
