/** FABLE Sec.18: every export must mention this, verbatim. */
export const EXPORT_ATTRIBUTION_LINES = [
  "Generated by Field Horizon",
  "Pomegranate Interactive",
  "Copyright © Pomegranate Interactive 2026",
];
