import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

import { downloadCsv, downloadDataUrl, downloadJson, downloadMarkdown } from "./exportFile";

describe("exportFile (FABLE Sec.18: every export carries the attribution block)", () => {
  let clickedHref = "";
  let clickedDownload = "";
  let createdBlobs: Blob[] = [];

  beforeEach(() => {
    createdBlobs = [];
    URL.createObjectURL = vi.fn((blob: Blob) => {
      createdBlobs.push(blob);
      return "blob:mock-url";
    });
    URL.revokeObjectURL = vi.fn();
    vi.spyOn(HTMLAnchorElement.prototype, "click").mockImplementation(function (this: HTMLAnchorElement) {
      clickedHref = this.href;
      clickedDownload = this.download;
    });
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  async function blobText(blob: Blob): Promise<string> {
    return await blob.text();
  }

  it("downloadJson wraps the data in a payload with the real attribution lines, not merged into the data itself", async () => {
    downloadJson(["not", "an", "object"], "test.json");

    expect(clickedDownload).toBe("test.json");
    const text = await blobText(createdBlobs[0]);
    const parsed = JSON.parse(text);
    expect(parsed.data).toEqual(["not", "an", "object"]);
    expect(parsed.attribution).toEqual([
      "Generated by Field Horizon",
      "Pomegranate Interactive",
      "Copyright © Pomegranate Interactive 2026",
    ]);
  });

  it("downloadMarkdown appends the attribution block after the real content", async () => {
    downloadMarkdown("# A heading\n\nBody text.", "test.md");

    const text = await blobText(createdBlobs[0]);
    expect(text).toContain("# A heading");
    expect(text).toContain("Generated by Field Horizon");
    expect(text).toContain("Copyright © Pomegranate Interactive 2026");
    expect(clickedDownload).toBe("test.md");
  });

  it("downloadCsv escapes commas/quotes/newlines and appends an attribution comment row", async () => {
    downloadCsv(
      [
        ["id", "title"],
        ["1", 'a title, with a comma and a "quote"'],
      ],
      "test.csv",
    );

    const text = await blobText(createdBlobs[0]);
    expect(text).toContain('"a title, with a comma and a ""quote"""');
    expect(text).toContain("Generated by Field Horizon");
  });

  it("downloadDataUrl sets the anchor href directly to the given data URL, no Blob involved", () => {
    downloadDataUrl("data:image/png;base64,Zm9v", "chart.png");
    expect(clickedHref).toBe("data:image/png;base64,Zm9v");
    expect(clickedDownload).toBe("chart.png");
  });
});
